sonar.projectKey=denfr18_beyond-diplegia
sonar.organization=denfr18
sonar.projectName=beyond-diplegia

sonar.sources=.
sonar.exclusions=**/.terraform/**,**/*.tfstate,**/*.tfstate.backup,**/tfplan,site/**,**/.github/**

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
